---
title: "Week 4 Practical"
output: html_document
date: "2025-10-28"
---

Relevant libraries:

```{r message=FALSE, warning=FALSE}
library(here)
library(dplyr)
library(tidyverse)
library(janitor)
library(tmap)
library(tmaptools)
library(sf)
library(OpenStreetMap)
library(plotly)
library(raster)
library(terra)
library(fs)
library(ggplot2)
library(countrycode)
```

Reading in the gender inequality data

```{r}
GI <- read_csv("https://hdr.undp.org/sites/default/files/2025_HDR/HDR25_Composite_indices_complete_time_series.csv")
```

```{r}
head(GI)
```

Reading in the spatial data

```{r include=FALSE}
world_shp <- st_read(here("prac4_data", "World_Countries_(Generalized).geojson"))
```

```{r}
head(world_shp)
```

Cleaning inequality data and adding difference column

```{r}
GI_diff <- GI%>%
  clean_names()%>%
  dplyr::select(iso3, country, gii_2019, gii_2010) %>%
  mutate(inequality_diff = gii_2019 - gii_2010)
head(GI_diff)
```

Adding country code column to inequality difference data

```{r warning=FALSE}

GI_diff_code <- countrycode(sourcevar = GI_diff$country,
                           origin = "country.name.en",
                           destination = "iso3c",
                           warn = TRUE,
                           nomatch = NA,
                           custom_dict = NULL,
                           custom_match = NULL,
                           origin_regex = NULL
                           )

GI_diff_code <- GI_diff%>%
  add_column(CODE = GI_diff_code, .before = "country")
head(GI_diff_code)
```

Adding country code column to world shape data

```{r}
world_shp_code <- countrycode(sourcevar = world_shp$COUNTRY, origin = "country.name.en", destination = "iso3c", warn = TRUE, nomatch = NA, custom_dict = NULL, custom_match = NULL, origin_regex = NULL)

world_shp_code <- world_shp %>% 
  add_column(CODE = world_shp_code, .before = "COUNTRY") 

head(world_shp_code)
```

Joining the data by code

```{r}
GI_diff_join <- world_shp_code%>%
  clean_names()%>%
  left_join(.,
            GI_diff_code,
            by = c("country" = "country"))
head(GI_diff_join)
```
